### ISSUE TITLE
highlevel TODO list

### ISSUE THREAD

**Issue by teto** [teto/mptcpanalyzer#4]
to reach feature parity with mptcpanalyzer:
- [ ] restore cache capabilities
- [ ] autocompletion of commands/parameters
- [ ] plugins
- [ ] ability to customize plots
- [ ] check source formatting
